# Generated by Django 4.2.23 on 2025-08-31 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignWorkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startdate', models.DateField(auto_now_add=True)),
                ('Enddate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=20, null=True)),
                ('Place', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('UserType', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapViewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Incident', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('AUTHORITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable')),
            ],
        ),
        migrations.CreateModel(
            name='IssueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Comment', models.CharField(blank=True, max_length=200, null=True)),
                ('ASSIGN_WORK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.assignworktable')),
                ('AUTHORITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Date', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contactnumber', models.BigIntegerField(blank=True, null=True)),
                ('Department', models.CharField(blank=True, max_length=20, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable')),
            ],
        ),
        migrations.AddField(
            model_name='authoritytable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.logintable'),
        ),
        migrations.AddField(
            model_name='assignworktable',
            name='AUTHORITY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable'),
        ),
        migrations.AddField(
            model_name='assignworktable',
            name='REPORT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.reporttable'),
        ),
        migrations.AddField(
            model_name='assignworktable',
            name='USERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable'),
        ),
        migrations.CreateModel(
            name='AlertTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('AUTHORITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable')),
            ],
        ),
    ]
