# Generated by Django 4.2.23 on 2025-09-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttable',
            name='Reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
