# Generated by Django 4.2.23 on 2025-09-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0002_complainttable_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
