# Generated by Django 4.2.23 on 2025-09-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0003_alerttable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignworktable',
            name='USERID',
        ),
        migrations.RemoveField(
            model_name='reporttable',
            name='AUTHORITY_ID',
        ),
        migrations.AddField(
            model_name='reporttable',
            name='USER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.usertable'),
        ),
        migrations.DeleteModel(
            name='ContactTable',
        ),
    ]
