# Generated by Django 4.2.23 on 2025-09-03 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0004_remove_assignworktable_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='AUTHORITY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable'),
        ),
    ]
