# Generated by Django 4.2.23 on 2025-09-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0005_reporttable_authority_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident', models.CharField(blank=True, max_length=200, null=True)),
                ('AUTHORITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.authoritytable')),
            ],
        ),
    ]
