# Generated by Django 4.2.23 on 2025-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0006_incidenttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritytable',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='mapviewtable',
            name='Time',
        ),
        migrations.AlterField(
            model_name='mapviewtable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
