# Generated by Django 4.2.24 on 2025-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0007_remove_authoritytable_name_remove_mapviewtable_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='Reply',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
