# Generated by Django 4.2.24 on 2025-09-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0008_alter_complainttable_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignworktable',
            name='AUTHORITY_ID',
        ),
        migrations.DeleteModel(
            name='IssueTable',
        ),
    ]
