# Generated by Django 4.2.23 on 2025-09-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0009_remove_assignworktable_authority_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignworktable',
            name='REPORT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roadapp.reporttable'),
        ),
    ]
