# Generated by Django 4.2.23 on 2025-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0010_alter_assignworktable_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapviewtable',
            name='Location',
        ),
        migrations.AddField(
            model_name='mapviewtable',
            name='Latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapviewtable',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapviewtable',
            name='Status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
