# Generated by Django 4.2.23 on 2025-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0012_remove_assignworktable_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignworktable',
            name='Status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
