# Generated by Django 4.2.23 on 2025-11-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0013_alter_assignworktable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
