# Generated by Django 4.2.23 on 2025-11-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0014_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritytable',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.department'),
        ),
    ]
