# Generated by Django 4.2.23 on 2025-11-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0015_alter_authoritytable_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttable',
            name='AUTHORITY_ID',
        ),
        migrations.AddField(
            model_name='reporttable',
            name='DEPARTMENT_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadapp.department'),
        ),
    ]
