# Generated by Django 4.2.24 on 2025-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0016_remove_reporttable_authority_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttable',
            name='Location',
        ),
        migrations.AddField(
            model_name='reporttable',
            name='Latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttable',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
