# Generated by Django 4.2.24 on 2025-11-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0017_remove_reporttable_location_reporttable_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttable',
            name='AUTHORITY_ID',
        ),
        migrations.DeleteModel(
            name='MapViewTable',
        ),
        migrations.DeleteModel(
            name='IncidentTable',
        ),
    ]
