# Generated by Django 4.2.24 on 2025-11-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0018_remove_incidenttable_authority_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertTable',
        ),
    ]
