# Generated by Django 4.2.24 on 2025-11-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadapp', '0019_delete_alerttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Image',
        ),
    ]
